function walkMapTree(callback, nodes, path) {
  nodes = nodes || rootNodes;
  path = path || ['HOME'];
  nodes.forEach(n => {
    callback(n, path);
    if (n.subNodes && n.subNodes.length) {
      const label = getNodeDisplayName(n, { fallback: 'Sub' });
      walkMapTree(callback, n.subNodes, path.concat([label]));
    }
  });
}

function isAutoGeneratedTitle(title) {
  const t = (title || '').trim();
  return !t || /^OPTION_NODE_\d+$/i.test(t);
}

function getNodeDisplayName(n, options = {}) {
  const maxLen = options.maxLen || 72;
  const fallback = options.fallback || 'Sin título';

  if (n.type === 'titulo') {
    const t = (n.content || n.title || '').trim();
    return t || 'Título sin texto';
  }

  if (n.type === 'region') {
    const t = (n.title || '').trim();
    return t && t !== 'REGIÓN' ? t : 'Región';
  }

  const title = (n.title || '').trim();
  if (title && !isAutoGeneratedTitle(title)) {
    return title.length > maxLen ? title.slice(0, maxLen) + '…' : title;
  }

  const content = extractNodeReadableText(n).trim();
  if (content) {
    const firstLine = content.split('\n').map(l => l.trim()).find(Boolean) || content;
    const preview = firstLine.slice(0, maxLen);
    return preview + (firstLine.length > maxLen ? '…' : '');
  }

  if (n.type === 'stack') return fallback === 'Sin título' ? 'Sub sin nombre' : fallback;
  if (n.type === 'document') return 'Documento vacío';
  if (n.type === 'link') return 'Enlace';
  if (n.type === 'photo') return 'Foto';
  return fallback;
}

function getNodeSearchText(n) {
  const parts = [
    n.title,
    n.content,
    n.documentContent,
    n.linkUrl,
    n.photoUrl,
    extractNodeReadableText(n),
    nodeTypeLabel(n)
  ];
  if (n.type === 'titulo') parts.unshift(n.content);
  return parts.filter(Boolean).join('\n').toLowerCase();
}

function getAllMapNodes() {
  const result = [];
  walkMapTree((n, path) => {
    if (n.type === 'region') return;
    const name = getNodeDisplayName(n);
    const preview = extractNodeReadableText(n).trim();
    const previewLine = preview.split('\n').map(l => l.trim()).find(Boolean) || '';
    const showPreview = previewLine && previewLine !== name && !name.includes(previewLine.slice(0, 24));
    result.push({
      node: n,
      id: n.id,
      path: path.join(' › '),
      label: name,
      typeLabel: nodeTypeLabel(n),
      preview: showPreview ? previewLine.slice(0, 96) : '',
      searchText: getNodeSearchText(n) + '\n' + path.join(' ').toLowerCase()
    });
  });
  return result;
}

function nodeTypeLabel(n) {
  if (n.type === 'stack') return 'sub';
  if (n.type === 'titulo') return 'título';
  if (n.type === 'document') return 'doc';
  if (n.type === 'link') return 'link';
  if (n.type === 'photo') return 'foto';
  return 'nodo';
}

function findNodeById(id, nodes) {
  nodes = nodes || rootNodes;
  for (let i = 0; i < nodes.length; i++) {
    const n = nodes[i];
    if (n.id === id) return n;
    if (n.subNodes && n.subNodes.length) {
      const found = findNodeById(id, n.subNodes);
      if (found) return found;
    }
  }
  return null;
}

function extractNodeReadableText(n) {
  if (n.type === 'titulo') return n.content || '';
  if (n.type === 'document') return n.documentContent || n.content || '';
  if (n.type === 'link') return n.linkUrl || n.content || '';
  if (n.type === 'photo') return n.photoUrl || n.content || '';
  if (n.mode === 'list' || n.mode === 'check') {
    return (n.items || [])
      .map(item => {
        const t = (item.text || '').trim();
        if (!t) return '';
        return n.mode === 'check' && item.checked ? '[x] ' + t : t;
      })
      .filter(Boolean)
      .join('\n');
  }
  return n.content || '';
}

function escapeMapSelectLabel(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/"/g, '&quot;');
}
